[package]
name = "neural"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
neuroflow = "0.2.0"
rand = "0.8.5"
serde_json = "1.0.116"

[patch.crates-io]
neuroflow = { path = "../patched-crates/NeuroFlow" }
